spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_svc?useSSL=false&serverTimezone=UTC
    username: root
    password: systemadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/